version: '3.3'

services:
  php:
      build:
        context: .
        dockerfile: dockerfile
      container_name: php8POO
      depends_on:
      - dbPOO
      image: php:8.0-apache
      volumes:
      - ./php:/var/www/html/
      ports:
      - 80:80
  dbPOO:
      container_name: mysql8POO
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment: 
        MYSQL_ROOT_PASSWORD: sdfjqgsfhg987
        MYSQL_DATABASE: PokeBase
        MYSQL_USER: dassoune
        MYSQL_PASSWORD: noemie0205
      ports:
      - 3306:3306
  phpmya:
      image: phpmyadmin/phpmyadmin:latest
      container_name: pmaPOO
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: dbPOO
        PMA_USER: dassoune
        PMA_PASSWORD: noemie0205
        UPLOAD_LIMIT: 320M
      ports:
      - 8899:80